# Generated by Django 5.2.7 on 2025-12-02 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('Id_rutina', models.AutoField(db_column='Id_rutina', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('Nivel', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], db_column='Nivel', default='Principiante', max_length=20)),
                ('Categoria', models.CharField(choices=[('Pecho', 'Pecho'), ('Espalda', 'Espalda'), ('Piernas', 'Piernas'), ('Hombros', 'Hombros'), ('Brazos', 'Brazos'), ('Abdomen', 'Abdomen'), ('Cardio', 'Cardio'), ('Full Body', 'Full Body')], db_column='Categoria', max_length=20)),
                ('Duracion_minutos', models.IntegerField(db_column='Duracion_minutos', default=30)),
                ('Calorias_estimadas', models.IntegerField(blank=True, db_column='Calorias_estimadas', null=True)),
                ('rutina_img', models.ImageField(blank=True, db_column='rutina_img', null=True, upload_to='rutinas/')),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='Estado', default='Activo', max_length=10)),
                ('Fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'db_table': 'rutina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('Id_ejercicio', models.AutoField(db_column='Id_ejercicio', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('Series', models.IntegerField(db_column='Series', default=3)),
                ('Repeticiones', models.CharField(db_column='Repeticiones', default='10-12', max_length=50)),
                ('Descanso_segundos', models.IntegerField(db_column='Descanso_segundos', default=60)),
                ('Orden', models.IntegerField(db_column='Orden', default=1)),
                ('ejercicio_img', models.ImageField(blank=True, db_column='ejercicio_img', null=True, upload_to='ejercicios/')),
                ('Id_rutina', models.ForeignKey(db_column='Id_rutina', on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='Rutinas.rutina')),
            ],
            options={
                'db_table': 'ejercicio',
                'ordering': ['Orden'],
                'managed': True,
            },
        ),
    ]
