# Generated by Django 5.2.6 on 2025-10-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historisl_Ventas',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, db_column='fecha_venta')),
                ('Monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'historial_ventas',
                'managed': False,
            },
        ),
    ]
