# Generated by Django 5.2.6 on 2025-10-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial_ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Ventas',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, db_column='fecha_venta')),
                ('Monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Fisico', 'Fisico'), ('Credito', 'Credito'), ('Debito', 'Debito'), ('PSE', 'PSE'), ('Nequi', 'Nequi')], db_column='metodo_pago', default='', max_length=30)),
            ],
            options={
                'db_table': 'historial_ventas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Historisl_Ventas',
        ),
    ]
