# Generated by Django 5.2.7 on 2025-11-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMembresia',
            fields=[
                ('Id_tipo_membresia', models.AutoField(db_column='Id_tipo_membresia', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
                ('Duracion_meses', models.IntegerField(choices=[(1, '1 Mes'), (3, '3 Meses'), (6, '6 Meses'), (12, '12 Meses (1 Año)'), (24, '24 Meses (2 Años)')], db_column='Duracion_meses', default=1)),
                ('Precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='Estado', default='Activo', max_length=8)),
                ('tipo_membresia_img', models.ImageField(blank=True, db_column='tipo_membresia_img', null=True, upload_to='tipos_membresia/')),
            ],
            options={
                'verbose_name': 'Tipo de Membresía',
                'verbose_name_plural': 'Tipos de Membresías',
                'db_table': 'tipo_membresia',
                'managed': False,
            },
        ),
    ]
