# Generated by Django 5.2.6 on 2025-10-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Id_venta', models.AutoField(db_column='Id_venta', primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('Total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
