# Generated by Django 5.2.6 on 2025-10-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('Id_asistencia', models.AutoField(db_column='Id_asistencia', primary_key=True, serialize=False)),
                ('Fecha_Hora', models.DateTimeField(auto_now_add=True, db_column='Fecha_Hora')),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
    ]
