# Generated by Django 5.2.6 on 2025-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('Id_detalle', models.AutoField(db_column='Id_detalle', primary_key=True, serialize=False)),
                ('Tipo_Pago', models.CharField(choices=[('PSE', 'PSE'), ('Efectivo', 'Efectivo'), ('Nequ', 'Nequ')], db_column='Tipo_Pago', default='', max_length=50)),
                ('Cantidad', models.IntegerField()),
                ('Subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
    ]
