# Generated by Django 5.2.7 on 2025-11-07 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Detalle_venta', '0001_initial'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='Id_venta',
            field=models.ForeignKey(blank=True, db_column='Id_venta', null=True, on_delete=django.db.models.deletion.CASCADE, to='Ventas.venta'),
        ),
    ]
