# Generated by Django 5.2.7 on 2025-12-02 20:40

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('usuariogym', 'Puede acceder a la vista  Usuariogym')],
            },
        ),
        migrations.CreateModel(
            name='User_Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('usariogym', 'Puede acceder a la vista usuariogym')],
            },
        ),
        migrations.CreateModel(
            name='User_Empleados',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=128)),
                ('last_login', models.DateTimeField(db_column='last_login', null=True)),
                ('is_superuser', models.BooleanField(db_column='is_superuser')),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('first_name', models.CharField(db_column='first_name', max_length=150)),
                ('last_name', models.CharField(db_column='last_name', max_length=150)),
                ('email', models.CharField(db_column='email', max_length=250)),
                ('is_staff', models.BooleanField(db_column='is_staff')),
                ('is_active', models.BooleanField(db_column='is_active')),
                ('date_joined', models.DateTimeField(db_column='date_joined')),
                ('Eps', models.CharField(db_column='Eps', max_length=50, null=True)),
                ('Sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='Sexo', default='', max_length=20, null=True)),
                ('Cedula', models.IntegerField(db_column='Cedula', null=True, unique=True)),
                ('empleados_img', models.CharField(db_column='empleados_img', max_length=100, null=True)),
                ('Huella_id', models.TextField(db_column='Huella_id', null=True)),
                ('Direccion', models.BinaryField(db_column='Direccion', max_length=50, null=True)),
                ('Celular', models.IntegerField(db_column='Celular', null=True)),
                ('template_huella', models.TextField(db_column='template_huella', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Empleados_user_empleados',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
