# Generated by Django 5.2.6 on 2025-10-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_empleados',
            name='Cedula',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Eps',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='', max_length=20, null=True),
        ),
    ]
