# Generated by Django 5.2.7 on 2025-12-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_empleados',
            name='Huella_id',
        ),
        migrations.RemoveField(
            model_name='user_empleados',
            name='template_huella',
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='empleados_img',
            field=models.ImageField(db_column='empleados_img', null=True, upload_to='usuarios/'),
        ),
    ]
