# Generated by Django 5.2.6 on 2025-10-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_alter_user_empleados_cedula_alter_user_empleados_eps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_empleados',
            options={'managed': False},
        ),
    ]
