# Generated by Django 5.2.6 on 2025-10-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0003_alter_user_empleados_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_empleados',
            table='Empleados_user_empleados',
        ),
    ]
