# Generated by Django 5.2.7 on 2025-11-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0004_alter_user_empleados_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_empleados',
            options={'managed': True},
        ),
    ]
