# Generated by Django 5.2.7 on 2025-11-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0004_alter_user_empleados_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('usariogym', 'Puede acceder a la vista usuariogym')],
            },
        ),
        migrations.AlterModelOptions(
            name='user_empleados',
            options={},
        ),
    ]
