# Generated by Django 5.2.7 on 2025-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0005_alter_user_empleados_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_empleados',
            name='Huella_id',
            field=models.IntegerField(db_column='Huella_id', null=True),
        ),
        migrations.AddField(
            model_name='user_empleados',
            name='empleados_img',
            field=models.CharField(db_column='empleados_img', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Cedula',
            field=models.IntegerField(db_column='Cedula', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Eps',
            field=models.CharField(db_column='Eps', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='Sexo', default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='email',
            field=models.CharField(db_column='email', max_length=250),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='is_active',
            field=models.BooleanField(db_column='is_active'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='last_login',
            field=models.DateTimeField(db_column='last_login', null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='password',
            field=models.CharField(db_column='password', max_length=128),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='username',
            field=models.CharField(db_column='username', max_length=150, unique=True),
        ),
    ]
