# Generated by Django 5.2.7 on 2025-11-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0005_alter_user_empleados_options'),
        ('Empleados', '0005_mimodelo'),
    ]

    operations = [
    ]
