# Generated by Django 5.2.7 on 2025-11-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0006_user_empleados_huella_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_empleados',
            name='Celular',
            field=models.IntegerField(db_column='Celular', null=True),
        ),
        migrations.AddField(
            model_name='user_empleados',
            name='Direccion',
            field=models.CharField(db_column='Direccion', max_length=50, null=True),
        ),
    ]
