# Generated by Django 5.2.7 on 2025-11-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0005_user_gym_alter_user_empleados_options'),
        ('Empleados', '0006_merge_0005_alter_user_empleados_options_0005_mimodelo'),
    ]

    operations = [
    ]
