# Generated by Django 5.2.7 on 2025-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0007_user_empleados_celular_user_empleados_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_empleados',
            name='Huella_id',
            field=models.TextField(db_column='Huella_id', null=True),
        ),
    ]
