# Generated by Django 5.2.7 on 2025-11-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0006_user_empleados_huella_id_and_more'),
        ('Empleados', '0007_merge_20251110_1544'),
    ]

    operations = [
    ]
