# Generated by Django 5.2.7 on 2025-11-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0008_merge_20251110_1723'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='MiModelo',
        # ),
        migrations.AddField(
            model_name='user_empleados',
            name='Celular',
            field=models.IntegerField(db_column='Celular', null=True),
        ),
        migrations.AddField(
            model_name='user_empleados',
            name='Direccion',
            field=models.CharField(db_column='Direccion', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_empleados',
            name='templates_huella',
            field=models.TextField(blank=True, db_column='templates_huella', null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Cedula',
            field=models.IntegerField(blank=True, db_column='Cedula', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Eps',
            field=models.CharField(blank=True, db_column='Eps', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Huella_id',
            field=models.TextField(blank=True, db_column='Huella_id', null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='Sexo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_column='date_joined'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='empleados_img',
            field=models.ImageField(blank=True, db_column='empleados_img', null=True, upload_to='usuarios/'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='first_name',
            field=models.CharField(blank=True, db_column='first_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login', null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='last_name',
            field=models.CharField(blank=True, db_column='last_name', max_length=150),
        ),
    ]
