# Generated by Django 5.2.7 on 2025-11-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0008_alter_user_empleados_huella_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_empleados',
            name='Direccion',
            field=models.BinaryField(db_column='Direccion', max_length=50, null=True),
        ),
    ]
