# Generated by Django 5.2.7 on 2025-11-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0009_delete_mimodelo_user_empleados_celular_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiModelo',
        ),
    ]
