# Generated by Django 5.2.7 on 2025-11-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0009_alter_user_empleados_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_empleados',
            name='template_huella',
            field=models.TextField(db_column='template_huella', null=True),
        ),
    ]
