# Generated by Django 5.2.7 on 2025-12-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0010_delete_mimodelo'),
        ('Empleados', '0010_user_empleados_template_huella'),
    ]

    operations = [
    ]
