# Generated by Django 5.2.7 on 2025-12-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0011_merge_20251201_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('usuariogym', 'Puede acceder a la vista  Usuariogym')],
            },
        ),
        migrations.AlterModelOptions(
            name='user_empleados',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='user_empleados',
            name='templates_huella',
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Cedula',
            field=models.IntegerField(db_column='Cedula', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Direccion',
            field=models.BinaryField(db_column='Direccion', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Eps',
            field=models.CharField(db_column='Eps', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Huella_id',
            field=models.TextField(db_column='Huella_id', null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='Sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_column='Sexo', default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='email',
            field=models.CharField(db_column='email', max_length=250),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='empleados_img',
            field=models.ImageField(db_column='empleados_img', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='is_active',
            field=models.BooleanField(db_column='is_active'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser'),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='last_login',
            field=models.DateTimeField(db_column='last_login', null=True),
        ),
        migrations.AlterField(
            model_name='user_empleados',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=150),
        ),
    ]
