# Generated by Django 5.2.6 on 2025-09-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('Id_categoria', models.AutoField(db_column='Id_categoria', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='Estado', default='Activo', max_length=10)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
    ]
