# Generated by Django 5.2.6 on 2025-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_membresia',
            fields=[
                ('Id_membresia', models.AutoField(db_column='Id_membresia', primary_key=True, serialize=False)),
                ('Precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pago_membresia',
                'managed': False,
            },
        ),
    ]
