# Generated by Django 5.2.6 on 2025-09-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('Id_producto', models.AutoField(db_column='Id_producto', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Descripcion', models.TextField(db_column='Descripcion')),
                ('Stock', models.IntegerField(db_column='Stock')),
                ('Precio_de_compra', models.DecimalField(db_column='Precio_de_compra', decimal_places=2, max_digits=10)),
                ('Precio_de_venta', models.DecimalField(db_column='Precio_de_venta', decimal_places=2, max_digits=10)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='Estado', default='Activo', max_length=8)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
