# Generated by Django 5.2.6 on 2025-10-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('Id_membresia', models.AutoField(db_column='Id_membresia', primary_key=True, serialize=False)),
                ('Fecha_inicio', models.DateTimeField(auto_now_add=True, db_column='Fecha_inicio')),
                ('Fecha_fin', models.DateField(db_column='Fecha_fin')),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='Estado', default='Activo', max_length=10)),
                ('Duracion_meses', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'membresia',
                'managed': False,
            },
        ),
    ]
