# Generated by Django 5.2.6 on 2025-10-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_usuario',
            fields=[
                ('Id_historial', models.AutoField(db_column='Id_historial', primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('Fecha_y_hora', models.DateTimeField(auto_now_add=True, db_column='Fecha_y_hora')),
            ],
            options={
                'db_table': 'historial_usuario',
                'managed': False,
            },
        ),
    ]
