# Generated by Django 5.2.7 on 2025-12-02 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salidas_Entradas',
            fields=[
                ('Id_SalEnt', models.AutoField(db_column='Id_SalEnt', primary_key=True, serialize=False)),
                ('Tipo_Cambio', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], db_column='EntSal', default='', max_length=30, null=True)),
                ('Precio_Afectado', models.DecimalField(db_column='Precio_Afectado', decimal_places=2, max_digits=10, null=True)),
                ('Stock_Afectado', models.IntegerField(db_column='Stock_Afectado', null=True)),
                ('Fecha_cambio', models.DateTimeField(db_column='Fecha_cambio', null=True)),
                ('Descripcion', models.TextField(db_column='Descripcion', null=True)),
                ('Id_ProAsoc', models.ForeignKey(db_column='Id_ProAsoc', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
            options={
                'db_table': 'Salidas_Entradas',
            },
        ),
    ]
