# Generated by Django 5.2.7 on 2025-12-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salidas_Entradas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salidas_entradas',
            options={'managed': False},
        ),
    ]
